### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
Ping. Ready to merge.

**Review by kalvdans — APPROVED** [review]
lgtm! But I have no merge rights.

**Review by compojoom — APPROVED** [review]

**Comment by fulldecent** [comment]
yup

**Comment by jon-signal** [comment]
Oops--sorry, @fulldecent, this one just totally slipped through the cracks. Thank you all the same for the contribution!

**Pull request closed without merging**
